spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sampledb?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: testuser
    password: testuser

  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
