spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sampledb?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: testuser
    password: testuser
